from __future__ import annotations

import argparse
from pathlib import Path

from phase4_llm_recommendation.pipeline import run_phase4


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Phase 4: LLM recommendation and reasoning engine."
    )
    parser.add_argument(
        "--candidate-context",
        default="phase3_retrieval_candidates/output/candidate_context.json",
        help="Path to candidate context JSON generated by Phase 3.",
    )
    parser.add_argument(
        "--model",
        default="gemini-1.5-flash",
        help="Google AI Studio model name (example: gemini-1.5-flash).",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=5,
        help="Number of recommendations to return.",
    )
    parser.add_argument(
        "--output-dir",
        default="phase4_llm_recommendation/output",
        help="Output folder for recommendations JSON.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = run_phase4(
        candidate_context_path=Path(args.candidate_context).resolve(),
        model_name=args.model,
        output_dir=Path(args.output_dir).resolve(),
        top_n=args.top_n,
    )
    print(f"Phase 4 completed. LLM recommendations saved at: {output_path}")


if __name__ == "__main__":
    main()

